### ISSUE TITLE
Ontobee is not pulling in just higher classes from Uberon

### ISSUE THREAD

**Issue by RDruzinsky** [obophenotype/ctenophore-ontology#4]
Example:

Keywords:  
masseter
  Search terms
Terms with 'masseter' included in their label:

http://purl.obolibrary.org/obo/UBERON_0001597 (UBERON):
masseter also in: CTENO
masseter muscle also in: CTENO
musculus masseter also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0001674 (UBERON):
masseteric veins also in: CTENO
masseteric vein also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0010939 (UBERON):
masseter, deep also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0011310 (UBERON):
masseteric cavity also in: CTENO
masseteric fossa also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0010995 (UBERON):
masseter, deep also in: CTENO
masseter, profundus also in: CTENO
deep layer of masseter also in: CTENO
deep part of masseter also in: CTENO
pars profunda (musculus masseter) also in: CTENO
pars profunda of masseter muscle also in: CTENO
pars profunda musculus masseterica also in: CTENO
deep part of masseter muscle also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0011140 (UBERON):
masseter, superficial also in: CTENO
pars superficialis (musculus masseter) also in: CTENO
superficial layer of masseter also in: CTENO
pars superficialis of masseter muscle also in: CTENO
superficial part of masseter also in: CTENO
pars profunda musculus masseterica superficialis also in: CTENO
superficial part of masseter muscle also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0011308 (UBERON):
masseter, pars reflexa also in: CTENO
pars reflexa of masseter also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0011313 (UBERON):
masseter, posterior also in: CTENO
posterior subdivision of masseter also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0011314 (UBERON):
masseter, anterior also in: CTENO
anterior subdivision of masseter also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0011321 (UBERON):
masseteric nerve also in: CTENO
nervus massetericus also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0013648 (UBERON):
masseteric artery also in: CTENO
arteria masseterica also in: CTENO
http://purl.obolibrary.org/obo/UBERON_0004506 (UBERON):
skeletal muscle tissue of masseter also in: CTENO

**Comment by cmungall** [comment]
not sure how often OntoBee loads, expect this should be done within the week

**Comment by cmungall** [comment]
OLS fixed: http://www.ebi.ac.uk/ols/search?q=masseter&ontology=cteno

not sure why ontobee still has a stale copy
